CREATE TABLE netology.ORDERS
(
    id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    customer_id INT,
    product_name VARCHAR NOT NULL,
    amount INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES netology.CUSTOMERS(id)
);

INSERT INTO netology.ORDERS (date, customer_id, product_name, amount)
VALUES (current_date, 3, 'laptop', 2);
