/*
2. Напишите скрипт создания таблицы со следующими параметрами:
 - название таблицы - `ORDERS`
 - содержит в себе 4 столбца - `id`, `date`, `customer_id`,`product_name`, `amount`
 - первичным ключом будет поле `id`, который инкрементируется каждый раз, при создании заказа
 - внешним ключом на поле `id` таблицы пользователей будет `customer_id`
 */

CREATE TABLE netology.ORDERS
(
    id INT generated BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TIMESTAMP NOT NULL,
    customer_id INT,
    product_name VARCHAR NOT NULL,
    amount INT NOT NULL,
    FOREIGN KEY (customer_id) REFERENCES netology.CUSTOMERS(id)
);

INSERT INTO netology.ORDERS (date, customer_id, product_name, amount)
VALUES (current_date, 3, 'laptop', 2);
